### ISSUE TITLE
v1.0.0.beta2 release checklist

### ISSUE THREAD

**Issue by Blahah** [Blahah/transrate#119]
- [x] compile latest transrate-tools for all platforms and include in `deps.yaml`
- [x] compile latest salmon for all platforms and include in `deps.yaml`
- [x] compile latest SNAP for all platforms and include in `deps.yaml`
- [x] remove samtools dependency
- [x] check tests & test coverage
